# Generated by Django 2.2.10 on 2021-07-05 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pollchoice',
            options={'verbose_name': 'Poll Choice', 'verbose_name_plural': 'Poll Choices'},
        ),
        migrations.RenameField(
            model_name='pollchoice',
            old_name='question_text',
            new_name='choice_text',
        ),
        migrations.RenameField(
            model_name='pollchoice',
            old_name='question_type',
            new_name='choice_type',
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='Anonymous user id')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Poll')),
                ('poll_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.PollChoice')),
            ],
            options={
                'verbose_name': "User's poll choice",
                'verbose_name_plural': "User's poll choices",
            },
        ),
    ]
