# Generated by Django 2.2.10 on 2021-07-05 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210705_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='anonymous_user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anonymous user id'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
