# Generated by Django 2.2.10 on 2021-07-05 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210705_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='user_id',
            new_name='user',
        ),
    ]
